### ISSUE TITLE
Routing table request/response functions

### ISSUE THREAD

**Issue by Vearol** [Vearol/TalTech-Network-Protocol#10]
Functions for sending our routing table, as well as updating from data received <br/>
1. Function for getting our table
* input - none
* output - bytearray, where each node takes 10 bytes(8 - Id, 2 - cost)
2. Function for updating our table
* input - bytearray, where each node takes 10 bytes(8 - Id, 2 - cost)
* output - none

<br/>
How to work with bytearrays? <br/>
1. Function bytes_to_number(input - bytearray, output - number). Could be made static, so you could use... <br/>
https://github.com/Vearol/TalTech-Network-Protocol/blob/8a69d563cd9a8f2862ce3cac451c801c8227e1c0/Server%26Client/src/production/header_parser.py#L13 <br/>
2. Function number_to_bytes(input - number, size of bytearray, output - bytearray) <br/>
https://github.com/Vearol/TalTech-Network-Protocol/blob/8a69d563cd9a8f2862ce3cac451c801c8227e1c0/Server%26Client/src/production/packet.py#L14

**Comment by 1n4r1** [comment]
Let's say we have 3 servers in our table 
```
id_a = b"\x41\x41\x41\x41\x41\x41\x41\x41"
id_b = b"\x42\x42\x42\x42\x42\x42\x42\x42"
id_c = b"\x43\x43\x43\x43\x43\x43\x43\x43"
```
and each cost of the path is 1.
```
costs= b"\x01"
```
and yesterday you said like this 
![image](https://user-images.githubusercontent.com/45119992/56513274-a444ed80-653a-11e9-8983-60e1c0a1db89.png)

today I said like this
![image](https://user-images.githubusercontent.com/45119992/56514030-dc4d3000-653c-11e9-8a9e-e256c7f21c65.png)
the first "column" of "output" is "type"
according to this, if I interpret literally, what I return is this
``` 
return b"\x41\x41\x41\x41\x41\x41\x41\x41\x01\x01\x42\x42\x42\x42\x42\x42\x42\x42\x01\x01\x43\x43\x43\x43\x43\x43\x43\x43\x01\x01"
```
Is this really what you want?

**Comment by Vearol** [comment]
![z1](https://user-images.githubusercontent.com/11599057/56513995-c2abe880-653c-11e9-9b64-fdf54c5904fe.png)
looks fine, I just corrected some bytes with cost, because x01x01 = 256 <br/>
but there is a little bug in parsing, found just now... I'm reading from the wrong side, not left -> right, but right -> left

**Comment by 1n4r1** [comment]
thx, but this thread is not for the bug, so plz move it to other thread

**Comment by Vearol** [comment]
ok... but the output example is exactly what I'm expecting to come

**Comment by 1n4r1** [comment]
OK, now I got what you mean
I did not understand some parts of the document on gitlab at that time. That's my fault.
![image](https://user-images.githubusercontent.com/45119992/56518480-428b8000-6548-11e9-82ae-d2a8a5bb72eb.png)
this example is fucking easy and we can write within 3 min.
so if there is a next time, if you think we are having stupid conversation plz give me something like this.

**Comment by inar1** [comment]
And I have one question, why this should be connected data of 10 bytes characters?
I can pass it with array or something iterable. It sounds easier to manage / debug.

**Comment by Vearol** [comment]
all of that crap is relatively easy, just a lot of annoying details
I think we will finish in a few days to run some final tests and be ready to test with a group

**Comment by 1n4r1** [comment]
since I'm talking to Tarmo so give me some time

**Comment by 1n4r1** [comment]
already implemented here
https://github.com/Vearol/TalTech-Network-Protocol/pull/19
